services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: iot
    ports: ["5432:5432"]
    volumes:
      - db-data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/passwords:/mosquitto/config/passwords
      - mosq-data:/mosquitto/data
    ports: ["1883:1883"]

  dev:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    ports:
      - "3000:3000"
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    depends_on: [db, mosquitto]
    environment:
      PG_URL: postgres://postgres:postgres@db:5432/iot
      MQTT_URL: mqtt://mosquitto:1883

volumes:
  db-data:
  mosq-data:
